Feat: sign message dialog [Draft]
Cypherock/cypherock-cysync pull request #150
Opened 2023-08-31 15:33 UTC by jhasuraj01

To Do
- [ ] Json View Custom Theme
- [ ] Device Sync Tab (3rd Screen)

2023-09-01 12:01 UTC, jhasuraj01 commented
![Screenshot_20230901_173027](https://github.com/Cypherock/cypherock-cysync/assets/44930179/4915adfd-2ccb-4e5b-9c0d-545c3b7f1030)
![Screenshot_20230901_173040](https://github.com/Cypherock/cypherock-cysync/assets/44930179/c3b8a4dc-a72f-43cd-a37c-1c6f200d66a1)
![Screenshot_20230901_173103](https://github.com/Cypherock/cypherock-cysync/assets/44930179/03419e26-f150-4a8a-acfc-8e63cf2f6c90)

2023-09-05 12:52 UTC, irshadCypherock requested changes

2023-09-05 12:52 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/SignMessage/Dialogs/ViewMessage.tsx
> +            style={{ background: 'none', paddingLeft: 0, paddingRight: 0 }}
Don't use style, use props existing props

2023-09-05 12:52 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/SignMessage/Dialogs/ViewJson.tsx
> +                  style={{ background: 'none' }}
Change this in `ui` package

2023-09-05 12:52 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/SignMessage/Dialogs/ViewJson.tsx
> +            style={{ background: 'none', paddingLeft: 0, paddingRight: 0 }}
Use props

2023-09-05 13:56 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/SignMessage/Dialogs/ViewJson.tsx
> +            style={{ background: 'none', paddingLeft: 0, paddingRight: 0 }}
Added utils props!

2023-09-05 13:56 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/SignMessage/Dialogs/ViewMessage.tsx
> +            style={{ background: 'none', paddingLeft: 0, paddingRight: 0 }}
Added utils props!

2023-09-06 13:56 UTC, irshadCypherock approved these changes

2023-09-06 13:57 UTC, merged