fix: sending the abort signal on closing all windows
Cypherock/cypherock-cysync pull request #151
Opened 2023-09-01 10:36 UTC by masterchief164

2023-09-01 10:36 UTC, rohanagarwal94 commented
Task linked: [PRF-6179 On cysync during onboarding the heading is being cut because of line height constraint](https://app.clickup.com/t/9002019994/PRF-6179)

2023-09-01 10:42 UTC, masterchief164 commented
The issue is limited to macOS so please test there.

2023-09-02 07:58 UTC, irshadCypherock requested changes

2023-09-02 07:58 UTC, irshadCypherock commented on apps/desktop/src/main/app.ts
> +    beforeQuitHook(app);
This will close the application as well. But we don't want to close it on mac

2023-10-17 06:38 UTC, closed without merging