Feat: Password Dialogs
Cypherock/cypherock-cysync pull request #158
Opened 2023-09-08 12:20 UTC by jhasuraj01

- [ ] Create Password Dialog
- [ ] Remove Password Dialog
- [ ] Change Password Dialog

2023-09-08 14:35 UTC, jhasuraj01 commented
Create Password Dialog:
![Screenshot_20230908_200322](https://github.com/Cypherock/cypherock-cysync/assets/44930179/8cee1d0c-ae42-47a8-8d7b-ed737ed0e3da)

Remove Password Dialog:
![Screenshot_20230908_200406](https://github.com/Cypherock/cypherock-cysync/assets/44930179/358e97bd-5c65-4668-9671-91a9ba381087)

Change Password Dialog:
![Screenshot_20230908_200425](https://github.com/Cypherock/cypherock-cysync/assets/44930179/fac59a3e-4e1c-48dd-88f9-906df018665e)

2023-09-13 10:03 UTC, irshadCypherock requested changes

2023-09-13 10:03 UTC, irshadCypherock commented on packages/cysync-core/src/components/GenericLoader.tsx
> +);
This already exists as `LoaderDialog` in the same folder

2023-09-13 10:03 UTC, irshadCypherock commented on packages/cysync-core/src/constants/i18n/en.ts
> +          info: 'Use 8 or more characters with a mix of letters, numbers & symbols',
Repeated text

2023-09-13 11:54 UTC, jhasuraj01 commented on packages/cysync-core/src/components/GenericLoader.tsx
> +);
deleted unwanted file

2023-09-13 12:29 UTC, jhasuraj01 commented on packages/cysync-core/src/constants/i18n/en.ts
> +          info: 'Use 8 or more characters with a mix of letters, numbers & symbols',
fix: reduced redundancy

2023-09-14 07:43 UTC, irshadCypherock approved these changes

2023-09-14 07:43 UTC, merged