fix: delete wallet on adding account to deleted wallet
Cypherock/cypherock-cysync pull request #161
Opened 2023-09-09 13:51 UTC by masterchief164

This PR fixes the issue [PRF-5666](https://app.clickup.com/t/9002019994/PRF-5666)

2023-09-09 13:51 UTC, rohanagarwal94 commented
Task linked: [PRF-5666 On cysync in add account flow when wallets are not present on device but cysync have in that case delete button isn't functional](https://app.clickup.com/t/9002019994/PRF-5666)

2023-09-26 11:58 UTC, irshadCypherock requested changes

2023-09-26 11:58 UTC, irshadCypherock commented on packages/cysync-core/src/hooks/useErrorHandler.ts
> +        console.log(selectedWallet);
Remove console log

2023-09-26 11:58 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AddAccount/index.tsx
> +                  textVariables={{ walletName: selectedWallet?.name }}
Add this in `Send`, `Receive` dialog as well

2023-10-16 14:02 UTC, irshadCypherock approved these changes

2023-10-16 14:11 UTC, merged