feat: card and vault authentication integration
Cypherock/cypherock-cysync pull request #172
Opened 2023-09-20 03:18 UTC by jhasuraj01

## TODO
- [x] X1 Card Authentication
- [x] X1 Vault Authentication

## Screenshots

### X1 Vault Authentication

![image](https://github.com/Cypherock/cypherock-cysync/assets/44930179/2a1ea694-556c-415d-a316-882bac450254)

![Screenshot_20230920_084532](https://github.com/Cypherock/cypherock-cysync/assets/44930179/d4d6306a-7323-480f-b1e0-1cc38a89152d)

### X1 Card Authentication

![Screenshot_20230920_084627](https://github.com/Cypherock/cypherock-cysync/assets/44930179/d3266b73-7d90-4d40-84a9-a58ea046d49c)

![Screenshot_20230920_084653](https://github.com/Cypherock/cypherock-cysync/assets/44930179/5cee956e-623f-4750-9f10-3a75d7401287)

### Error Handling

![Screenshot_20230920_084734](https://github.com/Cypherock/cypherock-cysync/assets/44930179/a7a3dc2e-57a1-4a84-82d8-d5291bb8abce)

![Screenshot_20230920_084800](https://github.com/Cypherock/cypherock-cysync/assets/44930179/90aae4ca-db16-4a23-9887-2988fe2beea9)

2023-09-21 07:47 UTC, irshadCypherock requested changes

2023-09-21 07:47 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AuthenticateX1Card/Dialogs/Email2FA.tsx
- The code here is very similar to Device Auth, create a common component for this which can be reused in both places.
- Email should be stored in the key value store
- Email should be prefilled from the key value store
- If the user clicks on `Skip` the email should be removed from key value store

2023-09-21 11:48 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/AuthenticateX1Card/Dialogs/Email2FA.tsx
Implemented

2023-09-22 10:55 UTC, irshadCypherock submitted a review, later dismissed

2023-09-26 13:45 UTC, merged