feat: contact support dialog
Cypherock/cypherock-cysync pull request #187
Opened 2023-09-27 08:44 UTC by jhasuraj01

2023-09-29 08:53 UTC, irshadCypherock requested changes

2023-09-29 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  ];
These should be the categories. 
```
'Complaint', 'Feedback', 'Others'
```

2023-09-29 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  ]);
Use `useMemo`

2023-09-29 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +      return;
```suggestion
    if (email === null || description === null || category === undefined) {
      setIsLoading(false);
      return;
    }
```

2023-09-29 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +    onNext();
```suggestion
    try {
      await sendFeedback(email, category.text, description);
      setIsLoading(false);
      onNext();
    } catch (apiError) {
      setError(
        ((apiError as AxiosError).response?.data as string) ??
          (apiError as AxiosError).message,
      );
      setIsLoading(false);
    }
```

2023-09-29 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +      name: lang.strings.dialogs.password.confimPassword.title,
Incorrect name

2023-09-30 09:28 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  ];
updated categories

2023-09-30 09:33 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +      return;
done

2023-09-30 09:36 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +    onNext();
done

2023-09-30 09:38 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +      name: lang.strings.dialogs.password.confimPassword.title,
name corrected

2023-09-30 09:42 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  ]);
replaced useEffect & setState with useMemo

2023-10-03 06:10 UTC, irshadCypherock approved these changes

2023-10-03 07:22 UTC, merged