fix: do not render fallback fonts
Cypherock/cypherock-cysync pull request #223
Opened 2023-10-25 12:17 UTC by jhasuraj01

References: -
- https://developers.google.com/fonts/docs/getting_started#use_font-display
- https://www.w3.org/TR/css-fonts-4/#font-display-desc

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-25 12:17 UTC, rohanagarwal94 commented
Task linked: [PRF-6272 On cysync the font is getting downloaded after opening](https://app.clickup.com/t/9002019994/PRF-6272)

2023-10-26 11:19 UTC, irshadCypherock requested changes

2023-10-26 11:19 UTC, irshadCypherock commented on apps/desktop/html/index.html
> +      href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1
It'll be better if we can package the font with the application

2023-10-28 08:46 UTC, irshadCypherock approved these changes

2023-10-28 09:10 UTC, merged