chore: remove non-functional question mark from text
Cypherock/cypherock-cysync pull request #229
Opened 2023-10-26 12:46 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/9002019994/PRF-6310
- remove non-functional question mark from text
- link feedback form with help-button

2023-10-26 12:46 UTC, rohanagarwal94 commented
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

2023-10-26 12:46 UTC, rohanagarwal94 commented
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

2023-10-26 12:46 UTC, rohanagarwal94 commented
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

2023-10-26 12:46 UTC, rohanagarwal94 commented
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

2023-10-26 12:46 UTC, rohanagarwal94 commented
Task linked: [PRF-6310 On cysync hide question marks and add support page in "Help ?" button](https://app.clickup.com/t/9002019994/PRF-6310)

2023-10-26 12:57 UTC, irshadCypherock requested changes

2023-10-26 12:57 UTC, irshadCypherock commented on packages/cysync-core/src/constants/i18n/en.ts
>                    // TODO: add functionality to 
Remove TODO's as well

2023-10-26 13:01 UTC, ujjwal-cyph commented on packages/cysync-core/src/constants/i18n/en.ts
>                    // TODO: add functionality to 
removed

2023-10-27 09:37 UTC, irshadCypherock approved these changes

2023-10-27 10:07 UTC, merged