feat: pre-fill feedback form with details from error dialog
Cypherock/cypherock-cysync pull request #245
Opened 2023-10-31 08:47 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/9002019994/PRF-6442

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 08:47 UTC, rohanagarwal94 commented
Task linked: [PRF-6442 Link pre-filled Support page to Help in error dialog](https://app.clickup.com/t/9002019994/PRF-6442)

2023-10-31 14:27 UTC, irshadCypherock requested changes

2023-10-31 14:27 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  errorCategory?: string;
Create a type for this

2023-11-01 14:41 UTC, ujjwal-cyph commented on packages/cysync-core/src/dialogs/ContactSupport/context/index.tsx
> +  errorCategory?: string;
added

2023-11-02 07:55 UTC, irshadCypherock approved these changes

2023-11-02 08:07 UTC, merged