feat: onboarding graphics and ui update
Cypherock/cypherock-cysync pull request #260
Opened 2023-11-02 21:08 UTC by jhasuraj01

2023-11-02 21:08 UTC, rohanagarwal94 commented
Task linked: [PRF-6306 On cysync graphics are missing for device and cards](https://app.clickup.com/t/9002019994/PRF-6306)

2023-11-03 09:36 UTC, irshadCypherock requested changes

2023-11-03 09:36 UTC, irshadCypherock commented on packages/cysync-core/src/components/AppUpdateFailedFallback.tsx
> +  CySyncDownloadRed,
```suggestion
  CySyncDownloadRedIcon,
```

2023-11-03 09:36 UTC, irshadCypherock commented on packages/cysync-core/src/pages/OnBoarding/AppUpdate/Dialogs/index.tsx
> +  CySyncDownloadGreen,
```suggestion
  CySyncDownloadGreenIcon,
```

2023-11-03 09:36 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Dialog/ErrorDialog.tsx
> +  CySyncDownloadRed,
```suggestion
  CySyncDownloadRedIcon,
```

2023-11-03 09:57 UTC, jhasuraj01 commented on packages/ui/src/components/molecules/Dialog/ErrorDialog.tsx
> +  CySyncDownloadRed,
Refactoring Done

2023-11-03 09:57 UTC, jhasuraj01 commented on packages/cysync-core/src/pages/OnBoarding/AppUpdate/Dialogs/index.tsx
> +  CySyncDownloadGreen,
Refactoring Done

2023-11-03 09:57 UTC, jhasuraj01 commented on packages/cysync-core/src/components/AppUpdateFailedFallback.tsx
> +  CySyncDownloadRed,
Refactoring Done

2023-11-03 10:38 UTC, irshadCypherock approved these changes

2023-11-03 10:38 UTC, merged