fix: dropdown overflow when wallet name is long
Cypherock/cypherock-cysync pull request #268
Opened 2023-11-06 05:07 UTC by irshadCypherock

2023-11-06 05:07 UTC, rohanagarwal94 commented
Task linked: [PRF-6522 On cysync in portfolio in wallet selection dropdown overflow can be seen in case of long wallet name](https://app.clickup.com/t/9002019994/PRF-6522)

2023-11-07 06:55 UTC, TejasvCypherock requested changes

2023-11-07 06:55 UTC, TejasvCypherock commented on packages/ui/src/components/molecules/DropDownListItem.tsx
> +            $restrictedItem={$restrictedItem}
The UI still needs some work 
![image](https://github.com/Cypherock/cypherock-cysync/assets/107414753/b5e2df7c-5885-47a3-8fb8-5e6f6ff2a549)

2023-11-07 14:37 UTC, TejasvCypherock approved these changes

2023-11-07 17:58 UTC, merged