feat: updated wallet recovery and wallet create dialog images
Cypherock/cypherock-cysync pull request #270
Opened 2023-11-07 03:20 UTC by jhasuraj01

2023-11-07 03:20 UTC, rohanagarwal94 commented
Task linked: [PRF-6306 On cysync graphics are missing for device and cards](https://app.clickup.com/t/9002019994/PRF-6306)

2023-11-08 18:16 UTC, irshadCypherock requested changes
Please fix the failing tests on CI

2023-11-08 18:16 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/GuidedFlow/context/index.tsx
> +} from '@cypherock/cysync-ui/src';
Do not import from `src`

2023-11-08 18:34 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/GuidedFlow/context/index.tsx
> +} from '@cypherock/cysync-ui/src';
fixed

2023-11-09 06:37 UTC, irshadCypherock approved these changes

2023-11-09 06:37 UTC, merged