feat: added solana receive on coin support
Cypherock/cypherock-cysync pull request #313
Opened 2023-12-05 11:15 UTC by irshadCypherock

2023-12-05 11:15 UTC, rohanagarwal94 commented
Task linked: [PRF-6585 Add Solana receive on coin support and CLI](https://app.clickup.com/t/9002019994/PRF-6585)

2023-12-06 06:56 UTC, TejasvCypherock approved these changes

2023-12-06 06:57 UTC, TejasvCypherock requested changes
Add changeset

2023-12-06 07:31 UTC, TejasvCypherock approved these changes

2023-12-06 08:05 UTC, merged