feat: added device error handling
Cypherock/cypherock-cysync pull request #34
Opened 2023-06-02 13:40 UTC by irshadCypherock

2023-06-08 10:01 UTC, TejasvCypherock requested changes

2023-06-08 10:01 UTC, ghost commented on apps/desktop/src/main/utils/device.ts
> -    await connectedDevice.connection.destroy();
Do we not need to destroy the connection anymore?

2023-06-08 10:01 UTC, ghost commented on packages/utils/src/config.ts
> +  throw new Error(`ENVIREMENT VARIABLE '${key}' NOT SPECIFIED.`);
Spell check

2023-06-08 10:01 UTC, ghost commented on packages/cysync-core/src/pages/OnBoarding/CardTraining/Dialogs/index.tsx
> +  }, []);
Since this is used everywhere, can we convert it into a hook or add it to useDeviceTask?

2023-06-09 09:19 UTC, irshadCypherock commented on apps/desktop/src/main/utils/device.ts
> -    await connectedDevice.connection.destroy();
It is executed when the connection is already destroyed. Check `apps/desktop/src/main/ipc/device.ts`

2023-06-10 01:02 UTC, TejasvCypherock approved these changes

2023-06-10 06:59 UTC, merged