feat: add token dialog
Cypherock/cypherock-cysync pull request #353
Opened 2023-12-28 12:10 UTC by jhasuraj01

2023-12-28 12:10 UTC, rohanagarwal94 commented
Task linked: [PRF-5006 Add Token on CySync/CLI](https://app.clickup.com/t/9002019994/PRF-5006)

2024-01-02 07:50 UTC, irshadCypherock requested changes

2024-01-02 07:50 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
> +export type AddTokenStatus = 'idle' | 'device' | 'sync' | 'done';
Unused variable

2024-01-02 07:50 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Wallet/index.tsx
> +          $buttonTwo={lang.strings.buttons.addToken}
I don't think the user can add token if he does not have an account

2024-01-02 08:45 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
> +export type AddTokenStatus = 'idle' | 'device' | 'sync' | 'done';
removed `AddTokenStatus`

2024-01-02 09:06 UTC, irshadCypherock approved these changes

2024-01-02 09:07 UTC, merged