fix: dropdown improvements and bug fixes
Cypherock/cypherock-cysync pull request #356
Opened 2024-01-06 11:46 UTC by jhasuraj01

2024-01-06 11:46 UTC, rohanagarwal94 commented
Task linked: [PRF-5006 Add Token on CySync/CLI](https://app.clickup.com/t/9002019994/PRF-5006)

2024-01-25 08:53 UTC, irshadCypherock requested changes

2024-01-25 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
> +import { syncAccounts, syncPriceHistories, syncPrices } from '~/actions';
Run `pnpm lint`, `pnpm pretty`

2024-01-25 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
>              : undefined;
For short form use `coin.abbr`

2024-01-25 08:53 UTC, irshadCypherock commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
> +        });
Use try catch and show errors if any

2024-01-29 06:52 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
> +        });
added try catch block and error logger

2024-01-29 14:31 UTC, jhasuraj01 commented on packages/cysync-core/src/dialogs/AddToken/context/index.tsx
>              : undefined;
updated

2024-01-30 08:33 UTC, irshadCypherock requested changes

2024-01-30 08:33 UTC, irshadCypherock commented on packages/coin-support-utils/src/db/account.ts
> +    );
This also updates the account, so this is no different than insertOrUpdate

2024-01-30 08:33 UTC, irshadCypherock commented on packages/coin-support-evm/src/services/helpers/contractTransactions.ts
> +    );
This will show the hidden tokens if a transaction is made to that account. Or when we do a database migration after adding additional tokens.

2024-01-30 08:39 UTC, jhasuraj01 commented on packages/coin-support-evm/src/services/helpers/contractTransactions.ts
> +    );
reverted back to `insertAccountIfNotExists`

2024-01-30 08:40 UTC, jhasuraj01 commented on packages/coin-support-utils/src/db/account.ts
> +    );
removed `...account` to avoid overwriting of unexpected properties

2024-01-30 12:52 UTC, irshadCypherock approved these changes

2024-01-30 17:58 UTC, merged