fix: graph not rendering and improved graph alignment
Cypherock/cypherock-cysync pull request #376
Opened 2024-01-24 23:25 UTC by jhasuraj01

2024-01-24 23:25 UTC, rohanagarwal94 commented
Task linked: [PRF-6662 On cysync graph isn't coming correct for cytest wallet](https://app.clickup.com/t/9002019994/PRF-6662)

2024-01-25 09:03 UTC, irshadCypherock requested changes

2024-01-25 09:03 UTC, irshadCypherock commented on packages/cysync-core/src/hooks/useGraph/index.tsx
> +        accounts: accountsWithoutPriceHistory,
Don't log public keys

2024-01-29 08:06 UTC, irshadCypherock approved these changes

2024-01-29 08:13 UTC, merged