feat: cySync log improvements (Part 1)
Cypherock/cypherock-cysync pull request #383
Opened 2024-02-01 09:53 UTC by jhasuraj01

2024-02-01 09:53 UTC, rohanagarwal94 commented
Task linked: [PRF-6931 CySync logs improvement for better diagnosis of user issues](https://app.clickup.com/t/9002019994/PRF-6931)

2024-02-20 08:58 UTC, irshadCypherock requested changes

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/actions/wallet/syncWallets.ts
> +      logger.warn('Wallet Sync Failed: Main App is not open');
```suggestion
      logger.warn('Wallet Sync Abort: Device is not on main');
```

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/actions/wallet/syncWallets.ts
> +      logger.warn('Wallet Sync Failed: Connection is not set up');
```suggestion
      logger.warn('Wallet Sync Abort: Connection is not set up');
```

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/actions/wallet/syncWallets.ts
> +      logger.warn('Wallet Sync Failed: Device is not connected');
```suggestion
      logger.warn('Wallet Sync Abort: Device is not connected');
```

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/actions/wallet/syncWallets.ts
> +      logger.warn('Wallet Sync Failed: Device is not authenticated');
```suggestion
      logger.warn('Wallet Sync Abort: Device is not authenticated');
```

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/actions/wallet/syncWallets.ts
> +      logger.warn('Wallet Sync Failed: No serial found for connected device');
```suggestion
      logger.warn('Wallet Sync Abort: No serial found for connected device');
```

2024-02-20 08:58 UTC, irshadCypherock commented on packages/cysync-core/src/components/Graph.tsx
> +  const handleWalletChangeProxy = useMemo((): typeof handleWalletChange => {
```suggestion
  const handleWalletChangeProxy = useCallback((): typeof handleWalletChange => {
```

2024-02-20 15:41 UTC, jhasuraj01 commented on packages/cysync-core/src/components/Graph.tsx
> +  const handleWalletChangeProxy = useMemo((): typeof handleWalletChange => {
Resolved as per discussion on slack.

2024-02-21 08:21 UTC, irshadCypherock approved these changes

2024-02-21 15:03 UTC, merged