feat: new sidebar ui
Cypherock/cypherock-cysync pull request #460
Opened 2024-05-10 11:38 UTC by jhasuraj01

- Decoupled input and options from `DropDown` Component
- used react-floating ui component for dropdowns
- updated sidebar ui

2024-05-18 09:54 UTC, irshadjsr21 requested changes

2024-05-18 09:54 UTC, irshadjsr21 commented on packages/ui/src/components/molecules/Dropdown/Dropdown.tsx
> +  // DropDownListContainer,
Remove comment

2024-05-20 15:27 UTC, jhasuraj01 commented on packages/ui/src/components/molecules/Dropdown/Dropdown.tsx
> +  // DropDownListContainer,
done

2024-05-22 09:58 UTC, irshadjsr21 approved these changes

2024-05-22 09:58 UTC, merged