Feat/inheritance pin recovery dialog
Cypherock/cypherock-cysync pull request #520
Opened 2024-08-16 12:37 UTC by AryanCypherock

2024-08-20 11:17 UTC, TejasvOnly requested changes

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/DecryptedPin.tsx
> +  }
This should be handled in previous tab according to figma

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/index.tsx
> +            heading={lang.strings.inheritanceSilverPlanPurchase.title}
Incorrect heading

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/WalletAuth.tsx
> +export const WalletAuth = () => {
Why is this component called `WalletAuth`?

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/Success.tsx
> +    <SuccessDialog
Need a confetti blast here

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/DecryptedPin.tsx
> +      />
This is different from figma

2024-08-20 11:17 UTC, TejasvOnly commented on packages/ui/src/components/molecules/MessageBox.tsx
> +export type MessageBoxType = 'info' | 'warning' | 'danger' | 'success';
I think figma design has been updated and this is no longer required

2024-08-20 11:17 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/DecryptedPin.tsx
> +  }
Also the design is different in figma

2024-08-20 11:54 UTC, AryanCypherock commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/WalletAuth.tsx
> +export const WalletAuth = () => {
I've changed the name from `WalletAuth` to `DecryptPin` as it describes the functionality of the component more

2024-08-20 13:41 UTC, AryanCypherock commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/DecryptedPin.tsx
> +      />
fixed

2024-08-20 18:46 UTC, AryanCypherock commented on packages/cysync-core/src/dialogs/Inheritance/PinRecovery/Dialogs/DecryptedPin.tsx
> +  }
- [x] moved to previous dialog
- [x] The figma design for this component is not updated, I've to use the existing ErrorDialog component

2024-08-22 06:13 UTC, TejasvOnly approved these changes

2024-08-22 06:13 UTC, merged