feat/inheritance edit encrypted message
Cypherock/cypherock-cysync pull request #521
Opened 2024-08-21 12:41 UTC by AryanCypherock

2024-08-29 14:25 UTC, irshadjsr21 requested changes

2024-08-29 14:25 UTC, irshadjsr21 commented on packages/cysync-core/src/actions/dialog/index.ts
> +export const openEditEncryptedMessageDialog = () =>
```suggestion
export const openInheritanceEditEncryptedMessageDialog = () =>
```

2024-08-29 14:25 UTC, irshadjsr21 commented on packages/cysync-core/src/actions/dialog/index.ts
>  export const openEditUserDetailsDialog = () =>
```suggestion
export const openInheritanceEditUserDetailsDialog = () =>
```

2024-08-29 14:25 UTC, irshadjsr21 commented on packages/cysync-core/src/dialogs/Inheritance/EditEncryptedMessage/Dialogs/Decryption.tsx
> +      <ReactPlayer
Try to use `Video` component
```suggestion
      <Video
```

2024-08-29 14:25 UTC, irshadjsr21 commented on packages/cysync-core/src/dialogs/index.tsx
> +import { InheritanceEditEncryptedMessageDialog } from './Inheritance/EditEncryptedMessage';
Import from `./Inheritance`

2024-09-14 02:25 UTC, TejasvOnly requested changes

2024-09-14 02:25 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EditEncryptedMessage/Dialogs/EditMessage.tsx
> +          </Button>
Requires secondary variant here

2024-09-14 07:50 UTC, TejasvOnly approved these changes

2024-09-14 07:59 UTC, merged