Feat/inheritance estate recovery dialog
Cypherock/cypherock-cysync pull request #545
Opened 2024-09-19 14:46 UTC by AryanCypherock

2024-09-20 12:00 UTC, TejasvOnly requested changes

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/index.tsx
> +            heading={lang.strings.inheritanceSilverPlanPurchase.title}
Incorrect heading

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/Dialogs/ClearDeviceData/AuthenticateClearData.tsx
> +        title={strings.tapCards.title}
Missing subtitle

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/Dialogs/Message.tsx
> +        </Container>
Missing confirmation checkbox

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/Dialogs/Success.tsx
> +        <Button onClick={() => onClose()} variant="secondary">
```suggestion
        <Button onClick={() => onClose()}>
```

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/context/index.tsx
> +  );
Use `useMemoReturn` instead of `useMemo`

2024-09-20 12:00 UTC, TejasvOnly commented on packages/cysync-core/src/store/dialog/index.ts
> +    isOpen: true,
```suggestion
    isOpen: false,
```

2024-09-26 10:26 UTC, irshadjsr21 requested changes

2024-09-26 10:26 UTC, irshadjsr21 commented on packages/cysync-core-constants/src/i18n/lang/ar-AE.json
> +    "resendOTP": "Resend OTP in ${timeout}s",
What is displayed after this timeout reaches 0?

2024-09-26 10:26 UTC, irshadjsr21 commented on packages/cysync-core/src/actions/dialog/index.ts
> +export const openEstateRecoveryDialog = () =>
```suggestion
export const openInheritanceEstateRecoveryDialog = () =>
```

2024-09-26 10:26 UTC, irshadjsr21 commented on packages/cysync-core/src/dialogs/Inheritance/EstateRecovery/context/index.tsx
> +  }, [wallets, deletedWallets]);
I don't think this is needed here

2024-09-26 14:23 UTC, merged