feat: added asset allocation component
Cypherock/cypherock-cysync pull request #65
Opened 2023-06-28 11:29 UTC by masterchief164

This PR adds the assets component in the portfolio page

2023-06-29 08:10 UTC, TejasvCypherock requested changes
Add a changeset

2023-06-29 08:10 UTC, ghost commented on packages/ui/src/assets/images/common/BitcoinIcon.tsx
Any specific reason for not adding an svg file and using it like other icons?

2023-06-29 08:10 UTC, ghost commented on packages/ui/src/assets/images/main-app/TriangleIcon.tsx
To keep it consistent with other files you can import this as svg and use rotate property for images to turn in upside down. and shouldn't this be in common as well?

2023-06-29 08:10 UTC, ghost commented on packages/ui/src/components/molecules/Table/AllocationShare.tsx
> +  </AllocationShareStyle>
There's also an additional state that should stack the percentage value over top of the bar

2023-06-29 08:10 UTC, ghost commented on packages/ui/src/components/molecules/Table/IconNameBox.tsx
> +}
Let's make it more generic like icon, title, and subtitle. instead of taking coin names as input to make it more generic

2023-06-29 08:10 UTC, ghost commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +              <TriangleIcon direction="up" />
Instead of creating two separate icons just add rotate property to a single one

2023-06-29 08:10 UTC, TejasvCypherock commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +  background: ${({ theme, index }) =>
On figma it seems these may not be alternate css but default and hover states, confirm with design team for the same

2023-06-29 08:10 UTC, TejasvCypherock commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +const TableHeaderStyle = styled.div`
Use th, td, and tr instead of divs

2023-06-29 08:10 UTC, TejasvCypherock commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +  padding?: string;
no need for this as spacing props should cover this

2023-06-29 08:10 UTC, TejasvCypherock commented on packages/ui/src/components/molecules/ProgressBar.tsx
> +  border-top-left-radius: ${({ progress }) => (progress === 100 ? 50 : 0)}px;
This breaks the UI for progress bar, check ProgressDialog

2023-06-29 08:10 UTC, TejasvCypherock requested changes
Add a changeset

2023-06-29 09:59 UTC, masterchief164 commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +const TableHeaderStyle = styled.div`
We cannot use flex in table elements.

2023-07-03 10:17 UTC, irshadCypherock requested changes

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/constants/routes/index.ts
> +    path: '/permission-setup',
This needs to be the first page

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/constants/routes/onboarding.ts
> +    path: '/',
Please revert this change

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Table/MutedTextBox.tsx
> +export const MutedTextBox: FC<MutedTextBoxProps> = ({ text }) => (
If these are specific to table molecule, prefix with `Table`. And if these are generic and can be used anywhere, move this outside `Table` folder.

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +  }
Utilities should be at the end
```suggestion
  &:hover {
    background: ${({ theme }) => theme.palette.background.sideBar};
  }
  ${flex}
  ${width}
  ${height}
  ${spacing}
```

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Table/TableBox.tsx
> +}) => <TableDataRowStyle {...props}>{children}</TableDataRowStyle>;
Need a line break after component declaration

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +  const handleClick = (columnName: string) => {
```suggestion
  const handleHeaderClick = (columnName: string) => {
```

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +      value: '$2.9827',
Amounts should not contain units, because that way: 
- We can write a generic sorting algorithm.
- Add unit only when displaying
```suggestion
      price: '16981.44',
      amount: '0.0178',
      value: '2.9827',
```

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +    }
We can add the sorting algorithm function for each column to the `headersData` array, and use them here.

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +        ))}
Try to use virtualized rendering. https://www.npmjs.com/package/react-virtualized

2023-07-03 10:17 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +  const [ascending, setAscending] = useState(true);
```suggestion
  const [isAscendingSort, setIsAscendingSort] = useState(true);
```

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/assets/images/common/index.ts
> +import { BitcoinIcon } from './BitcoinIcon';
Why are there 2 types of the same icon?

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Table/AllocationShare.tsx
> +};
`packages/ui` should not have any knowledge of the coins. Get these colors from `props`

2023-07-03 10:17 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Table/AssetIconNameBox.tsx
> +};
Since this component is mapping the coin name to the icons, it should exist inside `packages/cysync-core`

2023-07-05 06:48 UTC, irshadCypherock requested changes

2023-07-05 06:48 UTC, irshadCypherock commented on apps/desktop/package.json
> +  },
I don't think we need this

2023-07-05 06:48 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AllocationShare.tsx
> +import { AssetVariants } from '~/pages/MainApp/Components/AssetIconNameBox';
```suggestion
import { AssetVariants } from './AssetIconNameBox';
```

2023-07-05 06:48 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +export type NameVariants = 'Bitcoin' | 'Ethereum';
Duplicate of the type defined in `AssetIconNameBox`. Also, it'll be better if we used the `id` from `packages/coins` package.

2023-07-05 07:14 UTC, irshadCypherock commented on packages/cysync-core/src/pages/MainApp/Components/AssetAllocation.tsx
> +    },
This should have the `id` property, which will be used to display the icons. Currently, we are using `name` to display icon which maps to `CoinTypes` but they do not match.

Example: For bitcoin the data name is `Bitcoin` but in `CoinType` it's `bitcoin`

2023-07-05 07:55 UTC, irshadCypherock approved these changes

2023-07-05 07:55 UTC, merged