feat: wallet sync error dialog box added_PRF-4852
Cypherock/cypherock-cysync pull request #72
Opened 2023-07-04 10:54 UTC by subinsk

Figma Link: https://www.figma.com/file/UebPt5xS2ILrKbUndCZtCZ/Production?type=design&node-id=4871%3A272361&mode=dev

2023-07-04 10:54 UTC, rohanagarwal94 commented
Task linked: [PRF-4852 UI for Wallet Sync Dialog Box](https://app.clickup.com/t/9002019994/PRF-4852)

2023-07-05 08:58 UTC, irshadCypherock requested changes

2023-07-05 08:58 UTC, irshadCypherock commented on packages/ui/src/components/atoms/BlurOverlay.tsx
> +);
In the `DialogBox` component we have a prop `$isModal` which makes it a popup. Prefer using and modifying that instead of creating new one.

2023-07-05 08:58 UTC, irshadCypherock commented on packages/ui/src/components/molecules/Info.tsx
> +export const Info: FC<{
From the name, it's not clear what the component does and where it should be used.

2023-07-05 10:22 UTC, irshadCypherock approved these changes

2023-07-05 10:27 UTC, irshadCypherock requested changes
- The checkbox list does not match the figma design
<img width="518" alt="image" src="https://github.com/Cypherock/cypherock-cysync/assets/80461749/1552b018-199e-4af5-905f-459cb73af370">
<img width="468" alt="image" src="https://github.com/Cypherock/cypherock-cysync/assets/80461749/ddb23241-cd81-4a52-87e0-ee11b69e9921">

- Alignment issue
<img width="270" alt="image" src="https://github.com/Cypherock/cypherock-cysync/assets/80461749/8fecf760-679d-48d0-a8a2-6ce52078b075">

2023-07-06 06:43 UTC, irshadCypherock approved these changes

2023-07-06 06:44 UTC, merged